// <auto-generated />
using AssaTest.Infrastruture.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssaTest.Infrastruture.Migrations
{
    [DbContext(typeof(AppAssaContext))]
    [Migration("20231206144452_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssaTest.Domain.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Macar de auto Toyota",
                            Name = "Toyota",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Description = "Macar de auto Ford",
                            Name = "Ford",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Description = "Macar de auto BMW",
                            Name = "BMW",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
